import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Clean backend-only baseline. Supabase owns auth.users; Nest owns every public
 * application table and is the only supported application-data access path.
 */
export class InitialSchema1789960612000 implements MigrationInterface {
  name = 'InitialSchema1789960612000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE public.users (
        id uuid PRIMARY KEY REFERENCES auth.users(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        created_at timestamptz NOT NULL DEFAULT now(),
        name text,
        email text,
        meta_data jsonb,
        avatar text
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.groups (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        name varchar NOT NULL
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.user_group (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        user_id uuid NOT NULL REFERENCES public.users(id),
        role text NOT NULL DEFAULT 'member'
          CHECK (role IN ('owner', 'member')),
        UNIQUE (group_id, user_id)
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.bankaccounts (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        name text NOT NULL,
        type text NOT NULL,
        due_date date,
        removed boolean NOT NULL DEFAULT false,
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        user_id uuid NOT NULL REFERENCES public.users(id)
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.categories (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        name text NOT NULL,
        removed boolean NOT NULL DEFAULT false,
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.imports (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        "fileName" text NOT NULL,
        removed boolean NOT NULL DEFAULT false,
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.invites (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        email text NOT NULL,
        pending boolean NOT NULL DEFAULT true,
        UNIQUE (group_id, email)
      )
    `);
    await queryRunner.query(`
      CREATE TABLE public.transactions (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        description varchar,
        value real,
        date timestamp without time zone,
        bankaccount_id bigint NOT NULL REFERENCES public.bankaccounts(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        import_id bigint REFERENCES public.imports(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        installment_total integer,
        installment_current bigint,
        category_id bigint REFERENCES public.categories(id),
        credit_due_date date,
        observation text,
        removed boolean NOT NULL DEFAULT false,
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        to_be_considered_at date,
        calculated_date date
      )
    `);

    await queryRunner.query(`
      CREATE INDEX user_group_user_id_group_id_idx
      ON public.user_group (user_id, group_id)
    `);
    for (const table of [
      'bankaccounts',
      'categories',
      'imports',
      'invites',
      'transactions',
    ]) {
      await queryRunner.query(`
        CREATE INDEX ${table}_group_id_idx ON public.${table} (group_id)
      `);
    }

    for (const table of [
      'users',
      'groups',
      'user_group',
      'bankaccounts',
      'categories',
      'imports',
      'invites',
      'transactions',
    ]) {
      await queryRunner.query(
        `ALTER TABLE public.${table} DISABLE ROW LEVEL SECURITY`,
      );
    }

    await queryRunner.query('CREATE SCHEMA IF NOT EXISTS private');
    await queryRunner.query(`
      CREATE FUNCTION private.handle_new_user()
      RETURNS trigger
      LANGUAGE plpgsql
      SECURITY DEFINER
      SET search_path TO ''
      AS $function$
      BEGIN
        INSERT INTO public.users (id, email, name, avatar, meta_data)
        VALUES (
          NEW.id,
          NEW.email,
          NEW.raw_user_meta_data ->> 'name',
          NEW.raw_user_meta_data ->> 'avatar_url',
          NEW.raw_user_meta_data
        );
        RETURN NEW;
      END;
      $function$
    `);
    await queryRunner.query(`
      CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE FUNCTION private.handle_new_user()
    `);

    await queryRunner.query(`
      REVOKE ALL ON SCHEMA public
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE ALL ON SCHEMA private
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE ALL ON FUNCTION private.handle_new_user()
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      ALTER DEFAULT PRIVILEGES IN SCHEMA public
      REVOKE ALL PRIVILEGES ON TABLES
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      ALTER DEFAULT PRIVILEGES IN SCHEMA public
      REVOKE ALL PRIVILEGES ON SEQUENCES
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      ALTER DEFAULT PRIVILEGES IN SCHEMA public
      REVOKE EXECUTE ON FUNCTIONS
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`NOTIFY pgrst, 'reload schema'`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users',
    );
    await queryRunner.query(
      'DROP FUNCTION IF EXISTS private.handle_new_user()',
    );
    await queryRunner.query(`
      DROP TABLE IF EXISTS
        public.transactions,
        public.invites,
        public.imports,
        public.categories,
        public.bankaccounts,
        public.user_group,
        public.groups,
        public.users
      CASCADE
    `);
  }
}
