import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreditCardBillReconciliation1790650000000
  implements MigrationInterface
{
  name = 'CreditCardBillReconciliation1790650000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE public.transactions
      ADD CONSTRAINT transactions_id_group_id_unique UNIQUE (id, group_id)
    `);
    await queryRunner.query(`
      CREATE TABLE public.credit_card_bill_reconciliations (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        group_id bigint NOT NULL REFERENCES public.groups(id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        credit_account_id bigint NOT NULL,
        bill_month date NOT NULL,
        payment_transaction_id bigint NOT NULL,
        reconciled_bill_total numeric(14, 2) NOT NULL,
        CONSTRAINT credit_card_bill_reconciliations_month_check
          CHECK (bill_month = date_trunc('month', bill_month)::date),
        CONSTRAINT credit_card_bill_reconciliations_account_group_fk
          FOREIGN KEY (credit_account_id, group_id)
          REFERENCES public.bankaccounts(id, group_id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT credit_card_bill_reconciliations_payment_group_fk
          FOREIGN KEY (payment_transaction_id, group_id)
          REFERENCES public.transactions(id, group_id)
          ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT credit_card_bill_reconciliations_bill_unique
          UNIQUE (group_id, credit_account_id, bill_month),
        CONSTRAINT credit_card_bill_reconciliations_payment_unique
          UNIQUE (payment_transaction_id)
      )
    `);
    await queryRunner.query(`
      CREATE INDEX credit_card_bill_reconciliations_group_month_idx
      ON public.credit_card_bill_reconciliations
        (group_id, bill_month, credit_account_id)
    `);
    await queryRunner.query(`
      ALTER TABLE public.credit_card_bill_reconciliations
      DISABLE ROW LEVEL SECURITY
    `);
    await queryRunner.query(`
      REVOKE ALL PRIVILEGES ON public.credit_card_bill_reconciliations
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`
      REVOKE ALL PRIVILEGES ON SEQUENCE
        public.credit_card_bill_reconciliations_id_seq
      FROM PUBLIC, anon, authenticated, service_role
    `);
    await queryRunner.query(`NOTIFY pgrst, 'reload schema'`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      'DROP TABLE public.credit_card_bill_reconciliations',
    );
    await queryRunner.query(`
      ALTER TABLE public.transactions
      DROP CONSTRAINT transactions_id_group_id_unique
    `);
  }
}
