import { spawnSync } from "node:child_process";
import { chmodSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: repositoryRoot,
    encoding: "utf8",
    ...options,
  });

  if (result.error) {
    console.error(`${command} is unavailable: ${result.error.message}`);
    process.exit(1);
  }

  if (result.status !== 0) {
    const diagnostic = (result.stderr || "").trim();
    console.error(diagnostic || `${command} exited unsuccessfully.`);
    process.exit(result.status ?? 1);
  }

  return result;
}

function runSupabase(args) {
  return run(pnpm, ["exec", "supabase", ...args]);
}

function parseEnvironment(output) {
  return Object.fromEntries(
    output
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => /^[A-Z][A-Z0-9_]*=/.test(line))
      .map((line) => {
        const separator = line.indexOf("=");
        const name = line.slice(0, separator);
        const rawValue = line.slice(separator + 1);

        try {
          return [name, JSON.parse(rawValue)];
        } catch {
          return [name, rawValue.replace(/^['"]|['"]$/g, "")];
        }
      }),
  );
}

function localEnvironment() {
  const result = runSupabase(["status", "--output", "env"]);
  const environment = parseEnvironment(result.stdout);

  for (const required of ["API_URL", "DB_URL"]) {
    if (!environment[required]) {
      console.error(`Supabase status did not provide ${required}.`);
      process.exit(1);
    }
  }

  return environment;
}

function writePrivateEnvironment(path, lines) {
  writeFileSync(path, `${lines.join("\n")}\n`, { mode: 0o600 });
  chmodSync(path, 0o600);
}

function configureApplications(environment) {
  const publicKey = environment.PUBLISHABLE_KEY ?? environment.ANON_KEY;
  if (!publicKey) {
    console.error("Supabase status did not provide a browser-safe public key.");
    process.exit(1);
  }

  const apiEnvironment = [
    "# Generated by `pnpm infra:start`; local development only.",
    "NODE_ENV=development",
    "PORT=3000",
    `DATABASE_URL=${JSON.stringify(environment.DB_URL)}`,
    "DATABASE_SCHEMA=public",
    "DATABASE_SSL=false",
    `SUPABASE_URL=${JSON.stringify(environment.API_URL)}`,
    ...(environment.JWT_SECRET
      ? [`SUPABASE_JWT_SECRET=${JSON.stringify(environment.JWT_SECRET)}`]
      : []),
    "CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173",
  ];

  const webEnvironment = [
    "# Generated by `pnpm infra:start`; local development only.",
    "VITE_API_URL=http://localhost:3000",
    `VITE_SUPABASE_URL=${JSON.stringify(environment.API_URL)}`,
    `VITE_SUPABASE_KEY=${JSON.stringify(publicKey)}`,
  ];

  writePrivateEnvironment(
    join(repositoryRoot, "apps/api/.env.local"),
    apiEnvironment,
  );
  writePrivateEnvironment(
    join(repositoryRoot, "apps/web/.env.local"),
    webEnvironment,
  );
}

function printStatus(environment) {
  const databaseUrl = new URL(environment.DB_URL);

  console.log("Local Supabase is running.");
  console.log(`API/Auth: ${environment.API_URL}`);
  console.log(
    `Database: ${databaseUrl.hostname}:${databaseUrl.port}${databaseUrl.pathname}`,
  );
  if (environment.STUDIO_URL) console.log(`Studio: ${environment.STUDIO_URL}`);
  const emailUrl = environment.MAILPIT_URL ?? environment.INBUCKET_URL;
  if (emailUrl) {
    console.log(`Local email: ${emailUrl}`);
  }
}

const command = process.argv[2];

if (command === "start") {
  console.log(
    "Starting local Supabase (the first run downloads Docker images)...",
  );
  runSupabase(["start", "--output-format", "json"]);
  const environment = localEnvironment();
  configureApplications(environment);
  console.log("Building shared contracts required by TypeORM migrations...");
  run(pnpm, ["--filter", "@fina/types", "build"], { stdio: "inherit" });
  console.log("Applying TypeORM migrations to local Supabase PostgreSQL...");
  run(pnpm, ["--filter", "@fina/api", "migration:run"], {
    env: {
      ...process.env,
      DOTENV_CONFIG_PATH: ".env.local",
    },
    stdio: "inherit",
  });
  printStatus(environment);
  console.log("Local app configuration is ready. Run `pnpm dev`.");
} else if (command === "stop") {
  run(pnpm, ["exec", "supabase", "stop"], { stdio: "inherit" });
} else if (command === "status") {
  printStatus(localEnvironment());
} else {
  console.error("Usage: node scripts/local-infra.mjs <start|stop|status>");
  process.exit(1);
}
